language: generic
sudo: required

services:
    - docker

#the tag here doesn't really matter
#but it's good convention
before_install:
    - docker build -t peterprjevara/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true peterprjevara/docker-react npm run test

deploy:
    #several different providers are already pre-configured
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-113096848293"
    bucket_path: "docker-react"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY